### ISSUE TITLE
Deploying dacpac

### ISSUE THREAD

**Issue by chadnt** [JordanMarr/safe-stack-ssdt-starter#1]
Jordan, I appreciate the [blog post](https://jordanmarr.github.io/fsharp/safe-stack-ssdt-starter/) regarding using an SSDT option for SQLProvider. Hopefully, this is the right place to ask a question. Design time, everything works as expected - type providers reads the dacpac. I was surprised to learn that the dacpac is still required for runtime. Copying the file to the application folder fixes the problem, but I haven't yet figured out a good way to include it with regular deployment tools (like webdeploy). Do you perhaps have a recommendation?

**Comment by JordanMarr** [comment]
I'm glad you found it helpful. 🙂

The dacpac file does indeed need to be deployed with the application binaries.

The easiest way is to modify your Server.fsproj to include the .dacpac file with "CopyToOutputDirectory" to ensure that the .dacpac file will always exist in the app binaries.  (SQLProvider will search for it there in prod).

```
<ItemGroup>
      <None Include="..\{relative path to SSDT project}\ssdt\SafeTodo\bin\$(Configuration)\SafeTodoDB.dacpac" Link="SafeTodoDB.dacpac">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>

      {...other files...}

</ItemGroup>
```

In your Server.Database.fs file, you should also modify the SsdtPath binding so that it can build the project in either Debug or Release mode:

```F#
[<Literal>]
#if DEBUG
      let SsdtPath = __SOURCE_DIRECTORY__ + @"/../../ssdt/SafeTodoDB/bin/Debug/SafeTodoDB.dacpac"
#else
      let SsdtPath = __SOURCE_DIRECTORY__ + @"/../../ssdt/SafeTodoDB/bin/Release/SafeTodoDB.dacpac"
#endif
```


This assumes that the SSDT project has been built already to ensure that the .dacpac file exists.
So when creating a release, you must ensure that the SSDT project has been built in Release mode first to generate the .dacpac.
(For bigger projects, I usually have a FAKE build script that ensure that the SSDT project has been built first when creating a release deployment package.)
